name: Repo Stats After PR

on:
  pull_request:
    types: [opened, synchronize, closed]

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  repo-stats:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0 # Important: fetch all branches

      - name: Count files and lines (current branch)
        id: count
        run: |
          total_files=$(find . -type f -not -path "./.git/*" | wc -l)
          total_lines=$(find . -type f \( -name '*.js' -o -name '*.ts' -o -name '*.py' -o -name '*.java' \) -exec cat {} + | wc -l)
          echo "files=$total_files" >> $GITHUB_OUTPUT
          echo "lines=$total_lines" >> $GITHUB_OUTPUT

      - name: Count files and lines for all branches
        id: allbranches
        run: |
          git fetch --all
          branch_stats=""
          for branch in $(git branch -r | grep -v '\->' | sed 's/origin\///'); do
            git checkout -q $branch
            files=$(find . -type f -not -path "./.git/*" | wc -l)
            lines=$(find . -type f \( -name '*.js' -o -name '*.ts' -o -name '*.py' -o -name '*.java' \) -exec cat {} + | wc -l)
            branch_stats="${branch_stats}- **$branch**: $files files, $lines lines\n"
          done
            echo -e "branch_stats<<EOF\n${branch_stats}EOF" >> $GITHUB_OUTPUT

      - name: Comment on PR with full stats
        uses: peter-evans/create-or-update-comment@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.pull_request.number }}
          body: |
            📊 **Repo Stats After This PR**

            - Total files (this branch): ${{ steps.count.outputs.files }}
            - Total lines of code (this branch): ${{ steps.count.outputs.lines }}

            ### 📂 Stats for All Branches:
            ${{ steps.allbranches.outputs.branch_stats }}

      - name: Send alert to Google Chat
        run: |
          message="Repo Stats After PR: ${{ steps.count.outputs.files }} files, ${{ steps.count.outputs.lines }} lines"
          curl -X POST -H "Content-Type: application/json" \
            -d "{\"text\": \"$message\"}" \
            ${{ secrets.GCHAT_WEBHOOK }}
